name: ST-ShopPlus
main: net.starly.shopplus.ShopPlusMain
author: Starly Team
website: http://starly.kr/

description: ShopPlus Plugin.

softdepend:
  - ST-Core
  - ST-Money
  - Citizens
  - Vault

version: 1.1.3
api-version: 1.13

commands:
  shop:
    aliases: [상점]