name: ST-ShopPlus
main: net.starly.shopplus.ShopPlusMain
author: Starly Team
website: http://starly.kr/

description: Shop+ Plugin.

softdepend:
  - ST-Core
  - Vault

version: 1.0.6
api-version: 1.13

commands:
  shop:
    aliases: [상점]