name: ST-ShopPlus
main: net.starly.shopplus.ShopPlusMain
author: Starly Team
website: http://starly.kr/discord

description: Shop+ Plugin.

softdepend:
  - ST-Core
  - Vault

version: 1.0.4
api-version: 1.13

commands:
  shop:
    aliases: [ 상점 ]