name: ST-ShopPlus
main: net.starly.shopplus.ShopPlusMain
author: Starly Team
website: http://starly.kr/

description: Shop+ Plugin.

softdepend:
  - ST-Core
  - Vault
  - Citizens

version: 1.1.1
api-version: 1.13

commands:
  shop:
    aliases: [상점]