name: ST-ShopPlus
main: net.starly.shop.ShopMain
author: Starly Team
website: http://starly.kr/discord

description: Shop+ Plugin.

softdepend:
  - ST-Core

version: 1.0
api-version: 1.13

commands:
  shop:
    aliases: [ 상점 ]