package net.starly.shop.enums;

public enum InputType {
    ORIGIN_PRICE_SELL, ORIGIN_PRICE_BUY, MARKET_PRICE_SELL, MARKET_PRICE_BUY, STOCK, SET_NPC, MARKET_PRICE_MIN_SELL, MARKET_PRICE_MAX_SELL, MARKET_PRICE_MIN_BUY, MARKET_PRICE_MAX_BUY
}
